programacao = [
        "ALGORITMO", "PROGRAMA", "CODIGO", "VARIAVEL", "FUNCAO",
        "CLASSE", "OBJETO", "HERANCA", "LOOP", "CONDICAO",
        "PYTHON", "JAVA", "JAVASCRIPT", "HTML", "CSS",
        "REACT", "NODE", "SQL", "BANCO", "DADOS",
        "SERVIDOR", "CLIENTE", "API", "JSON", "DEBUG",
        "COMPILADOR", "INTERPRETADOR", "FRAMEWORK", "BIBLIOTECA", "GIT",
        "GITHUB", "VERSIONAMENTO", "DEPLOY", "CLOUD", "HOSPEDAGEM",
        "DOMINIO", "BACKEND", "FRONTEND", "FULLSTACK", "SCRIPT",
        "TERMINAL", "LINUX", "WINDOWS", "MACOS", "INTELIGENCIA",
        "ARTIFICIAL", "MACHINE", "LEARNING", "DADOS", "SEGURANCA"
    ]